2025-05-17 04:28:41 | ERROR | stderr | Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
2025-05-17 04:28:41 | ERROR | stderr | 
2025-05-17 04:28:43 | ERROR | stderr | Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:05,  1.75s/it]
2025-05-17 04:28:43 | ERROR | stderr | 
2025-05-17 04:28:44 | ERROR | stderr | Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:03<00:03,  1.84s/it]
2025-05-17 04:28:44 | ERROR | stderr | 
2025-05-17 04:28:46 | ERROR | stderr | Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:05<00:01,  1.81s/it]
2025-05-17 04:28:46 | ERROR | stderr | 
2025-05-17 04:28:48 | ERROR | stderr | Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:07<00:00,  1.82s/it]
2025-05-17 04:28:48 | ERROR | stderr | 
2025-05-17 04:28:48 | ERROR | stderr | Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:07<00:00,  1.81s/it]
2025-05-17 04:28:48 | ERROR | stderr | 
2025-05-17 04:28:48 | ERROR | stderr | 
2025-05-17 04:29:08 | INFO | model_worker | Loading the model ['Qwen2.5-7B-Instruct'] on worker f4237bba, worker type: vLLM worker...
2025-05-17 04:29:08 | INFO | model_worker | Register to controller
2025-05-17 04:29:08 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m939946[0m]
2025-05-17 04:29:08 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2025-05-17 04:29:08 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2025-05-17 04:29:08 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:30011[0m (Press CTRL+C to quit)
2025-05-17 04:29:27 | INFO | stdout | [CompletionOutput(index=0, text='To', token_ids=(1249,), cumulative_logprob=-8.344646857949556e-07, logprobs=[{1249: Logprob(logprob=-8.344646857949556e-07, rank=1, decoded_token='To')}], finish_reason=None, stop_reason=None), CompletionOutput(index=1, text='To', token_ids=(1249,), cumulative_logprob=-8.344646857949556e-07, logprobs=[{1249: Logprob(logprob=-8.344646857949556e-07, rank=1, decoded_token='To')}], finish_reason=None, stop_reason=None), CompletionOutput(index=2, text='To', token_ids=(1249,), cumulative_logprob=-8.344646857949556e-07, logprobs=[{1249: Logprob(logprob=-8.344646857949556e-07, rank=1, decoded_token='To')}], finish_reason=None, stop_reason=None), CompletionOutput(index=3, text='To', token_ids=(1249,), cumulative_logprob=-8.344646857949556e-07, logprobs=[{1249: Logprob(logprob=-8.344646857949556e-07, rank=1, decoded_token='To')}], finish_reason=None, stop_reason=None)]
2025-05-17 04:29:27 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60204 - "[1mPOST /worker_generate HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-05-17 04:29:27 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-05-17 04:29:27 | ERROR | stderr | Traceback (most recent call last):
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
2025-05-17 04:29:27 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     raise exc
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 04:29:27 | ERROR | stderr |     raise exc
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 04:29:27 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
2025-05-17 04:29:27 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
2025-05-17 04:29:27 | ERROR | stderr |     await self.app(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
2025-05-17 04:29:27 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 04:29:27 | ERROR | stderr |     raise exc
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 04:29:27 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
2025-05-17 04:29:27 | ERROR | stderr |     response = await f(request)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
2025-05-17 04:29:27 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
2025-05-17 04:29:27 | ERROR | stderr |     return await dependant.call(**values)
2025-05-17 04:29:27 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 199, in api_generate
2025-05-17 04:29:27 | ERROR | stderr |     output = await worker.generate(params)
2025-05-17 04:29:27 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 157, in generate
2025-05-17 04:29:27 | ERROR | stderr |     async for x in self.generate_stream(params):
2025-05-17 04:29:27 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 154, in generate_stream
2025-05-17 04:29:27 | ERROR | stderr |     yield (json.dumps(ret) + "\0").encode()
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/json/__init__.py", line 231, in dumps
2025-05-17 04:29:27 | ERROR | stderr |     return _default_encoder.encode(obj)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/json/encoder.py", line 199, in encode
2025-05-17 04:29:27 | ERROR | stderr |     chunks = self.iterencode(o, _one_shot=True)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/json/encoder.py", line 257, in iterencode
2025-05-17 04:29:27 | ERROR | stderr |     return _iterencode(o, 0)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/json/encoder.py", line 179, in default
2025-05-17 04:29:27 | ERROR | stderr |     raise TypeError(f'Object of type {o.__class__.__name__} '
2025-05-17 04:29:27 | ERROR | stderr | TypeError: Object of type Logprob is not JSON serializable
2025-05-17 04:29:27 | INFO | stdout | [CompletionOutput(index=0, text='To', token_ids=(1249,), cumulative_logprob=-0.000576449150685221, logprobs=[{1249: Logprob(logprob=-0.000576449150685221, rank=1, decoded_token='To')}], finish_reason=None, stop_reason=None), CompletionOutput(index=1, text='To', token_ids=(1249,), cumulative_logprob=-0.000576449150685221, logprobs=[{1249: Logprob(logprob=-0.000576449150685221, rank=1, decoded_token='To')}], finish_reason=None, stop_reason=None), CompletionOutput(index=2, text='To', token_ids=(1249,), cumulative_logprob=-0.000576449150685221, logprobs=[{1249: Logprob(logprob=-0.000576449150685221, rank=1, decoded_token='To')}], finish_reason=None, stop_reason=None), CompletionOutput(index=3, text='To', token_ids=(1249,), cumulative_logprob=-0.000576449150685221, logprobs=[{1249: Logprob(logprob=-0.000576449150685221, rank=1, decoded_token='To')}], finish_reason=None, stop_reason=None)]
2025-05-17 04:29:27 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60216 - "[1mPOST /worker_generate HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-05-17 04:29:27 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-05-17 04:29:27 | ERROR | stderr | Traceback (most recent call last):
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
2025-05-17 04:29:27 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     raise exc
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 04:29:27 | ERROR | stderr |     raise exc
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 04:29:27 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
2025-05-17 04:29:27 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
2025-05-17 04:29:27 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
2025-05-17 04:29:27 | ERROR | stderr |     await self.app(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
2025-05-17 04:29:27 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 04:29:27 | ERROR | stderr |     raise exc
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 04:29:27 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
2025-05-17 04:29:27 | ERROR | stderr |     response = await f(request)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
2025-05-17 04:29:27 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
2025-05-17 04:29:27 | ERROR | stderr |     return await dependant.call(**values)
2025-05-17 04:29:27 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 199, in api_generate
2025-05-17 04:29:27 | ERROR | stderr |     output = await worker.generate(params)
2025-05-17 04:29:27 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 157, in generate
2025-05-17 04:29:27 | ERROR | stderr |     async for x in self.generate_stream(params):
2025-05-17 04:29:27 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 154, in generate_stream
2025-05-17 04:29:27 | ERROR | stderr |     yield (json.dumps(ret) + "\0").encode()
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/json/__init__.py", line 231, in dumps
2025-05-17 04:29:27 | ERROR | stderr |     return _default_encoder.encode(obj)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/json/encoder.py", line 199, in encode
2025-05-17 04:29:27 | ERROR | stderr |     chunks = self.iterencode(o, _one_shot=True)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/json/encoder.py", line 257, in iterencode
2025-05-17 04:29:27 | ERROR | stderr |     return _iterencode(o, 0)
2025-05-17 04:29:27 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/json/encoder.py", line 179, in default
2025-05-17 04:29:27 | ERROR | stderr |     raise TypeError(f'Object of type {o.__class__.__name__} '
2025-05-17 04:29:27 | ERROR | stderr | TypeError: Object of type Logprob is not JSON serializable
2025-05-17 04:29:53 | INFO | model_worker | Send heart beat. Models: ['Qwen2.5-7B-Instruct']. Semaphore: Semaphore(value=1022, locked=False). call_ct: 2. worker_id: f4237bba. 
2025-05-17 04:30:29 | ERROR | stderr | [32mINFO[0m:     Shutting down
2025-05-17 04:30:29 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2025-05-17 04:30:29 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2025-05-17 04:30:29 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m939946[0m]
