2025-05-17 03:41:55 | ERROR | stderr | Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
2025-05-17 03:41:55 | ERROR | stderr | 
2025-05-17 03:41:56 | ERROR | stderr | Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:05,  1.75s/it]
2025-05-17 03:41:56 | ERROR | stderr | 
2025-05-17 03:41:58 | ERROR | stderr | Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:03<00:03,  1.84s/it]
2025-05-17 03:41:58 | ERROR | stderr | 
2025-05-17 03:42:00 | ERROR | stderr | Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:05<00:01,  1.81s/it]
2025-05-17 03:42:00 | ERROR | stderr | 
2025-05-17 03:42:02 | ERROR | stderr | Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:07<00:00,  1.82s/it]
2025-05-17 03:42:02 | ERROR | stderr | 
2025-05-17 03:42:02 | ERROR | stderr | Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:07<00:00,  1.82s/it]
2025-05-17 03:42:02 | ERROR | stderr | 
2025-05-17 03:42:02 | ERROR | stderr | 
2025-05-17 03:42:20 | INFO | model_worker | Loading the model ['Qwen2.5-7B-Instruct'] on worker 400761d0, worker type: vLLM worker...
2025-05-17 03:42:20 | INFO | model_worker | Register to controller
2025-05-17 03:42:21 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m902947[0m]
2025-05-17 03:42:21 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2025-05-17 03:42:21 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2025-05-17 03:42:21 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:30011[0m (Press CTRL+C to quit)
2025-05-17 03:43:01 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50158 - "[1mPOST /worker_generate HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-05-17 03:43:01 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-05-17 03:43:01 | ERROR | stderr | Traceback (most recent call last):
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
2025-05-17 03:43:01 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     raise exc
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 03:43:01 | ERROR | stderr |     raise exc
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 03:43:01 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
2025-05-17 03:43:01 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
2025-05-17 03:43:01 | ERROR | stderr |     await self.app(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
2025-05-17 03:43:01 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 03:43:01 | ERROR | stderr |     raise exc
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 03:43:01 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
2025-05-17 03:43:01 | ERROR | stderr |     response = await f(request)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
2025-05-17 03:43:01 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
2025-05-17 03:43:01 | ERROR | stderr |     return await dependant.call(**values)
2025-05-17 03:43:01 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 196, in api_generate
2025-05-17 03:43:01 | ERROR | stderr |     output = await worker.generate(params)
2025-05-17 03:43:01 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 154, in generate
2025-05-17 03:43:01 | ERROR | stderr |     async for x in self.generate_stream(params):
2025-05-17 03:43:01 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 100, in generate_stream
2025-05-17 03:43:01 | ERROR | stderr |     sampling_params = SamplingParams(
2025-05-17 03:43:01 | ERROR | stderr | TypeError: Unexpected keyword argument 'use_beam_search'
2025-05-17 03:43:01 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50168 - "[1mPOST /worker_generate HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-05-17 03:43:01 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-05-17 03:43:01 | ERROR | stderr | Traceback (most recent call last):
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
2025-05-17 03:43:01 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     raise exc
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 03:43:01 | ERROR | stderr |     raise exc
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 03:43:01 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
2025-05-17 03:43:01 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
2025-05-17 03:43:01 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
2025-05-17 03:43:01 | ERROR | stderr |     await self.app(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
2025-05-17 03:43:01 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 03:43:01 | ERROR | stderr |     raise exc
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 03:43:01 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
2025-05-17 03:43:01 | ERROR | stderr |     response = await f(request)
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
2025-05-17 03:43:01 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-05-17 03:43:01 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
2025-05-17 03:43:01 | ERROR | stderr |     return await dependant.call(**values)
2025-05-17 03:43:01 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 196, in api_generate
2025-05-17 03:43:01 | ERROR | stderr |     output = await worker.generate(params)
2025-05-17 03:43:01 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 154, in generate
2025-05-17 03:43:01 | ERROR | stderr |     async for x in self.generate_stream(params):
2025-05-17 03:43:01 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 100, in generate_stream
2025-05-17 03:43:01 | ERROR | stderr |     sampling_params = SamplingParams(
2025-05-17 03:43:01 | ERROR | stderr | TypeError: Unexpected keyword argument 'use_beam_search'
2025-05-17 03:43:06 | INFO | model_worker | Send heart beat. Models: ['Qwen2.5-7B-Instruct']. Semaphore: Semaphore(value=1022, locked=False). call_ct: 2. worker_id: 400761d0. 
2025-05-17 03:43:51 | INFO | model_worker | Send heart beat. Models: ['Qwen2.5-7B-Instruct']. Semaphore: Semaphore(value=1022, locked=False). call_ct: 2. worker_id: 400761d0. 
2025-05-17 03:44:31 | INFO | stdout | [32mINFO[0m:     127.0.0.1:54144 - "[1mPOST /worker_generate HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-05-17 03:44:31 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-05-17 03:44:31 | ERROR | stderr | Traceback (most recent call last):
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
2025-05-17 03:44:31 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     raise exc
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 03:44:31 | ERROR | stderr |     raise exc
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 03:44:31 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
2025-05-17 03:44:31 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
2025-05-17 03:44:31 | ERROR | stderr |     await self.app(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
2025-05-17 03:44:31 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 03:44:31 | ERROR | stderr |     raise exc
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 03:44:31 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
2025-05-17 03:44:31 | ERROR | stderr |     response = await f(request)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
2025-05-17 03:44:31 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
2025-05-17 03:44:31 | ERROR | stderr |     return await dependant.call(**values)
2025-05-17 03:44:31 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 196, in api_generate
2025-05-17 03:44:31 | ERROR | stderr |     release_worker_semaphore()
2025-05-17 03:44:31 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 154, in generate
2025-05-17 03:44:31 | ERROR | stderr |     pass
2025-05-17 03:44:31 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 100, in generate_stream
2025-05-17 03:44:31 | ERROR | stderr |     sampling_params = SamplingParams(
2025-05-17 03:44:31 | ERROR | stderr | TypeError: Unexpected keyword argument 'use_beam_search'
2025-05-17 03:44:31 | INFO | stdout | [32mINFO[0m:     127.0.0.1:54160 - "[1mPOST /worker_generate HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-05-17 03:44:31 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-05-17 03:44:31 | ERROR | stderr | Traceback (most recent call last):
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
2025-05-17 03:44:31 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     raise exc
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 03:44:31 | ERROR | stderr |     raise exc
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 03:44:31 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
2025-05-17 03:44:31 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
2025-05-17 03:44:31 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
2025-05-17 03:44:31 | ERROR | stderr |     await self.app(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
2025-05-17 03:44:31 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-05-17 03:44:31 | ERROR | stderr |     raise exc
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-05-17 03:44:31 | ERROR | stderr |     await app(scope, receive, sender)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
2025-05-17 03:44:31 | ERROR | stderr |     response = await f(request)
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
2025-05-17 03:44:31 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-05-17 03:44:31 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
2025-05-17 03:44:31 | ERROR | stderr |     return await dependant.call(**values)
2025-05-17 03:44:31 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 196, in api_generate
2025-05-17 03:44:31 | ERROR | stderr |     release_worker_semaphore()
2025-05-17 03:44:31 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 154, in generate
2025-05-17 03:44:31 | ERROR | stderr |     pass
2025-05-17 03:44:31 | ERROR | stderr |   File "/fs-computility/mabasic/fanyuchen/openr/reason/llm_service/workers/vllm_worker.py", line 100, in generate_stream
2025-05-17 03:44:31 | ERROR | stderr |     sampling_params = SamplingParams(
2025-05-17 03:44:31 | ERROR | stderr | TypeError: Unexpected keyword argument 'use_beam_search'
2025-05-17 03:44:36 | INFO | model_worker | Send heart beat. Models: ['Qwen2.5-7B-Instruct']. Semaphore: Semaphore(value=1020, locked=False). call_ct: 4. worker_id: 400761d0. 
2025-05-17 03:44:40 | ERROR | stderr | [32mINFO[0m:     Shutting down
2025-05-17 03:44:40 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2025-05-17 03:44:40 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2025-05-17 03:44:40 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m902947[0m]
2025-05-17 03:44:40 | ERROR | stderr | Exception ignored in atexit callback: <function shutdown at 0x7fdaa94c4550>
2025-05-17 03:44:40 | ERROR | stderr | Traceback (most recent call last):
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
2025-05-17 03:44:40 | ERROR | stderr |     return func(*args, **kwargs)
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/ray/_private/worker.py", line 1950, in shutdown
2025-05-17 03:44:40 | ERROR | stderr |     from ray.dag.compiled_dag_node import _shutdown_all_compiled_dags
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/ray/dag/__init__.py", line 1, in <module>
2025-05-17 03:44:40 | ERROR | stderr |     from ray.dag.dag_node import DAGNode
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/ray/dag/dag_node.py", line 2, in <module>
2025-05-17 03:44:40 | ERROR | stderr |     from ray.experimental.channel.auto_transport_type import AutoTransportType
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/ray/experimental/channel/__init__.py", line 21, in <module>
2025-05-17 03:44:40 | ERROR | stderr |     from ray.experimental.channel.torch_tensor_nccl_channel import TorchTensorNcclChannel
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/ray/experimental/channel/torch_tensor_nccl_channel.py", line 361, in <module>
2025-05-17 03:44:40 | ERROR | stderr |     class _TorchTensorNcclChannel(ChannelInterface):
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/site-packages/ray/experimental/channel/torch_tensor_nccl_channel.py", line 472, in _TorchTensorNcclChannel
2025-05-17 03:44:40 | ERROR | stderr |     ) -> Optional[List[_TorchTensorMetadata]]:
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/typing.py", line 309, in inner
2025-05-17 03:44:40 | ERROR | stderr |     return cached(*args, **kwds)
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/typing.py", line 403, in __getitem__
2025-05-17 03:44:40 | ERROR | stderr |     return self._getitem(self, parameters)
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/typing.py", line 530, in Optional
2025-05-17 03:44:40 | ERROR | stderr |     return Union[arg, type(None)]
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/typing.py", line 309, in inner
2025-05-17 03:44:40 | ERROR | stderr |     return cached(*args, **kwds)
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/typing.py", line 403, in __getitem__
2025-05-17 03:44:40 | ERROR | stderr |     return self._getitem(self, parameters)
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/typing.py", line 520, in Union
2025-05-17 03:44:40 | ERROR | stderr |     return _UnionGenericAlias(self, parameters, name="Optional")
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/typing.py", line 1019, in __init__
2025-05-17 03:44:40 | ERROR | stderr |     super().__init__(origin, inst=inst, name=name)
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/typing.py", line 951, in __init__
2025-05-17 03:44:40 | ERROR | stderr |     self.__slots__ = None  # This is not documented.
2025-05-17 03:44:40 | ERROR | stderr |   File "/root/miniconda3/envs/open_reasoner/lib/python3.10/typing.py", line 986, in __setattr__
2025-05-17 03:44:40 | ERROR | stderr |     def __setattr__(self, attr, val):
2025-05-17 03:44:40 | ERROR | stderr | KeyboardInterrupt:
